# powershell script to explore the Enphase Envoy local API

# set this to whatever your Gateway's IP address is
$ipaddr="192.168.1.135"

echo "info"
curl -f -k -H 'Accept: application/json' -H 'Authorization: Bearer eyJraWQiOiI3ZDEwMDA1ZC03ODk5LTRkMGQtYmNiNC0yNDRmOThlZTE1NmIiLCJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI0ODI0MzcwMDczMDAiLCJpc3MiOiJFbnRyZXoiLCJlbnBoYXNlVXNlciI6Im93bmVyIiwiZXhwIjoxODAyMTkwMTE5LCJpYXQiOjE3NzA2NTQxMTksImp0aSI6ImNlZTFhZjI0LTU1MzQtNDZkYi04ZWM0LTNlZWVlMDM0YTgxNiIsInVzZXJuYW1lIjoibWFya21jaW50eXJlOTlAZ29vZ2xlbWFpbC5jb20ifQ.SJeIHOLW1B96ejeDimbR8yMCMcNhPTF6vLaIulqHEiGmN6Rlvczu58XwJsdqaesfAF477WiGb-tDxVHcxmGN2g' -X GET https://$ipaddr/info

echo "ivp/ensemble/device_list"
curl -f -k -H 'Accept: application/json' -H 'Authorization: Bearer eyJraWQiOiI3ZDEwMDA1ZC03ODk5LTRkMGQtYmNiNC0yNDRmOThlZTE1NmIiLCJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI0ODI0MzcwMDczMDAiLCJpc3MiOiJFbnRyZXoiLCJlbnBoYXNlVXNlciI6Im93bmVyIiwiZXhwIjoxODAyMTkwMTE5LCJpYXQiOjE3NzA2NTQxMTksImp0aSI6ImNlZTFhZjI0LTU1MzQtNDZkYi04ZWM0LTNlZWVlMDM0YTgxNiIsInVzZXJuYW1lIjoibWFya21jaW50eXJlOTlAZ29vZ2xlbWFpbC5jb20ifQ.SJeIHOLW1B96ejeDimbR8yMCMcNhPTF6vLaIulqHEiGmN6Rlvczu58XwJsdqaesfAF477WiGb-tDxVHcxmGN2g' -X GET https://$ipaddr/ivp/ensemble/device_list

echo "ivp/meters"
curl -f -k -H 'Accept: application/json' -H 'Authorization: Bearer eyJraWQiOiI3ZDEwMDA1ZC03ODk5LTRkMGQtYmNiNC0yNDRmOThlZTE1NmIiLCJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI0ODI0MzcwMDczMDAiLCJpc3MiOiJFbnRyZXoiLCJlbnBoYXNlVXNlciI6Im93bmVyIiwiZXhwIjoxODAyMTkwMTE5LCJpYXQiOjE3NzA2NTQxMTksImp0aSI6ImNlZTFhZjI0LTU1MzQtNDZkYi04ZWM0LTNlZWVlMDM0YTgxNiIsInVzZXJuYW1lIjoibWFya21jaW50eXJlOTlAZ29vZ2xlbWFpbC5jb20ifQ.SJeIHOLW1B96ejeDimbR8yMCMcNhPTF6vLaIulqHEiGmN6Rlvczu58XwJsdqaesfAF477WiGb-tDxVHcxmGN2g' -X GET https://$ipaddr/ivp/meters
echo "ivp/meters/readings"
curl -f -k -H 'Accept: application/json' -H 'Authorization: Bearer eyJraWQiOiI3ZDEwMDA1ZC03ODk5LTRkMGQtYmNiNC0yNDRmOThlZTE1NmIiLCJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI0ODI0MzcwMDczMDAiLCJpc3MiOiJFbnRyZXoiLCJlbnBoYXNlVXNlciI6Im93bmVyIiwiZXhwIjoxODAyMTkwMTE5LCJpYXQiOjE3NzA2NTQxMTksImp0aSI6ImNlZTFhZjI0LTU1MzQtNDZkYi04ZWM0LTNlZWVlMDM0YTgxNiIsInVzZXJuYW1lIjoibWFya21jaW50eXJlOTlAZ29vZ2xlbWFpbC5jb20ifQ.SJeIHOLW1B96ejeDimbR8yMCMcNhPTF6vLaIulqHEiGmN6Rlvczu58XwJsdqaesfAF477WiGb-tDxVHcxmGN2g' -X GET https://$ipaddr/ivp/meters/readings
echo "ivp/meters/gridReading"
curl -f -k -H 'Accept: application/json' -H 'Authorization: Bearer eyJraWQiOiI3ZDEwMDA1ZC03ODk5LTRkMGQtYmNiNC0yNDRmOThlZTE1NmIiLCJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI0ODI0MzcwMDczMDAiLCJpc3MiOiJFbnRyZXoiLCJlbnBoYXNlVXNlciI6Im93bmVyIiwiZXhwIjoxODAyMTkwMTE5LCJpYXQiOjE3NzA2NTQxMTksImp0aSI6ImNlZTFhZjI0LTU1MzQtNDZkYi04ZWM0LTNlZWVlMDM0YTgxNiIsInVzZXJuYW1lIjoibWFya21jaW50eXJlOTlAZ29vZ2xlbWFpbC5jb20ifQ.SJeIHOLW1B96ejeDimbR8yMCMcNhPTF6vLaIulqHEiGmN6Rlvczu58XwJsdqaesfAF477WiGb-tDxVHcxmGN2g' -X GET https://$ipaddr/ivp/meters/gridReading

echo "ivp/pdm/energy"
curl -f -k -H 'Accept: application/json' -H 'Authorization: Bearer eyJraWQiOiI3ZDEwMDA1ZC03ODk5LTRkMGQtYmNiNC0yNDRmOThlZTE1NmIiLCJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI0ODI0MzcwMDczMDAiLCJpc3MiOiJFbnRyZXoiLCJlbnBoYXNlVXNlciI6Im93bmVyIiwiZXhwIjoxODAyMTkwMTE5LCJpYXQiOjE3NzA2NTQxMTksImp0aSI6ImNlZTFhZjI0LTU1MzQtNDZkYi04ZWM0LTNlZWVlMDM0YTgxNiIsInVzZXJuYW1lIjoibWFya21jaW50eXJlOTlAZ29vZ2xlbWFpbC5jb20ifQ.SJeIHOLW1B96ejeDimbR8yMCMcNhPTF6vLaIulqHEiGmN6Rlvczu58XwJsdqaesfAF477WiGb-tDxVHcxmGN2g' -X GET https://$ipaddr/ivp/pdm/energy

echo "ivp/livedata/status"
curl -f -k -H 'Accept: application/json' -H 'Authorization: Bearer eyJraWQiOiI3ZDEwMDA1ZC03ODk5LTRkMGQtYmNiNC0yNDRmOThlZTE1NmIiLCJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI0ODI0MzcwMDczMDAiLCJpc3MiOiJFbnRyZXoiLCJlbnBoYXNlVXNlciI6Im93bmVyIiwiZXhwIjoxODAyMTkwMTE5LCJpYXQiOjE3NzA2NTQxMTksImp0aSI6ImNlZTFhZjI0LTU1MzQtNDZkYi04ZWM0LTNlZWVlMDM0YTgxNiIsInVzZXJuYW1lIjoibWFya21jaW50eXJlOTlAZ29vZ2xlbWFpbC5jb20ifQ.SJeIHOLW1B96ejeDimbR8yMCMcNhPTF6vLaIulqHEiGmN6Rlvczu58XwJsdqaesfAF477WiGb-tDxVHcxmGN2g' -X GET https://$ipaddr/ivp/livedata/status

echo "api/v1/production"
curl -f -k -H 'Accept: application/json' -H 'Authorization: Bearer eyJraWQiOiI3ZDEwMDA1ZC03ODk5LTRkMGQtYmNiNC0yNDRmOThlZTE1NmIiLCJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI0ODI0MzcwMDczMDAiLCJpc3MiOiJFbnRyZXoiLCJlbnBoYXNlVXNlciI6Im93bmVyIiwiZXhwIjoxODAyMTkwMTE5LCJpYXQiOjE3NzA2NTQxMTksImp0aSI6ImNlZTFhZjI0LTU1MzQtNDZkYi04ZWM0LTNlZWVlMDM0YTgxNiIsInVzZXJuYW1lIjoibWFya21jaW50eXJlOTlAZ29vZ2xlbWFpbC5jb20ifQ.SJeIHOLW1B96ejeDimbR8yMCMcNhPTF6vLaIulqHEiGmN6Rlvczu58XwJsdqaesfAF477WiGb-tDxVHcxmGN2g' -X GET https://$ipaddr/api/v1/production
echo "api/v1/production/inverters"
curl -f -k -H 'Accept: application/json' -H 'Authorization: Bearer eyJraWQiOiI3ZDEwMDA1ZC03ODk5LTRkMGQtYmNiNC0yNDRmOThlZTE1NmIiLCJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI0ODI0MzcwMDczMDAiLCJpc3MiOiJFbnRyZXoiLCJlbnBoYXNlVXNlciI6Im93bmVyIiwiZXhwIjoxODAyMTkwMTE5LCJpYXQiOjE3NzA2NTQxMTksImp0aSI6ImNlZTFhZjI0LTU1MzQtNDZkYi04ZWM0LTNlZWVlMDM0YTgxNiIsInVzZXJuYW1lIjoibWFya21jaW50eXJlOTlAZ29vZ2xlbWFpbC5jb20ifQ.SJeIHOLW1B96ejeDimbR8yMCMcNhPTF6vLaIulqHEiGmN6Rlvczu58XwJsdqaesfAF477WiGb-tDxVHcxmGN2g' -X GET https://$ipaddr/api/v1/production/inverters

echo "inventory - includes battery"
curl -f -k -H 'Accept: application/json' -H 'Authorization: Bearer eyJraWQiOiI3ZDEwMDA1ZC03ODk5LTRkMGQtYmNiNC0yNDRmOThlZTE1NmIiLCJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI0ODI0MzcwMDczMDAiLCJpc3MiOiJFbnRyZXoiLCJlbnBoYXNlVXNlciI6Im93bmVyIiwiZXhwIjoxODAyMTkwMTE5LCJpYXQiOjE3NzA2NTQxMTksImp0aSI6ImNlZTFhZjI0LTU1MzQtNDZkYi04ZWM0LTNlZWVlMDM0YTgxNiIsInVzZXJuYW1lIjoibWFya21jaW50eXJlOTlAZ29vZ2xlbWFpbC5jb20ifQ.SJeIHOLW1B96ejeDimbR8yMCMcNhPTF6vLaIulqHEiGmN6Rlvczu58XwJsdqaesfAF477WiGb-tDxVHcxmGN2g' -X GET https://$ipaddr/ivp/ensemble/inventory